### ISSUE TITLE
The question regarding how objects in each viewpoint and image captions are obtained

### ISSUE THREAD

**Issue by xiyuying** [GengzeZhou/NavGPT#13]
Hello, may I ask which specific part of your code uses BLIP2 to add captions to images? Additionally, in your paper, you mentioned using Faster-RCNN as the Visual Foundation Model for object detection, but it doesn't seem to be reflected in the code. So how are the objects in each viewpoint obtained?

**Comment by GengzeZhou** [comment]
This data preprocessing step is not included in the reference and validation. However, such a preprocess is as simple as rendering every viewpoint in MP3D and using BLIP2/ Faster-RCNN to caption/ extract objects. For your reference, you can find the relevant code [here](https://github.com/cshizhe/VLN-HAMT/blob/main/preprocess/precompute_img_features_vit.py).

Moreover, there are many following works investigating better ways of converting visual observation into language description, e.g., 3D scene graphs or topological maps [1, 2, 3], I recommend leveraging more advanced VLMs (GPT4o/ LLama3.2/ Llava-OV) to generate sence description.

[1] [Jia, Baoxiong, et al. "Sceneverse: Scaling 3d vision-language learning for grounded scene understanding." European Conference on Computer Vision. Springer, Cham, 2025.](https://arxiv.org/pdf/2401.09340)

[2] [Chen, Jiaqi, et al. "Mapgpt: Map-guided prompting with adaptive path planning for vision-and-language navigation." Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers). 2024.](https://arxiv.org/abs/2401.07314)

[3] [Qiao, Yanyuan, et al. "Open-Nav: Exploring Zero-Shot Vision-and-Language Navigation in Continuous Environment with Open-Source LLMs." arXiv preprint arXiv:2409.18794 (2024).](https://arxiv.org/pdf/2409.18794)

**Comment by xiyuying** [comment]
> This data preprocessing step is not included in the reference and validation. However, such a preprocess is as simple as rendering every viewpoint in MP3D and using BLIP2/ Faster-RCNN to caption/ extract objects. For your reference, you can find the relevant code [here](https://github.com/cshizhe/VLN-HAMT/blob/main/preprocess/precompute_img_features_vit.py).
> 
> Moreover, there are many following works investigating better ways of converting visual observation into language description, e.g., 3D scene graphs or topological maps [1, 2, 3], I recommend leveraging more advanced VLMs (GPT4o/ LLama3.2/ Llava-OV) to generate sence description.
> 
> [1] [Jia, Baoxiong, et al. "Sceneverse: Scaling 3d vision-language learning for grounded scene understanding." European Conference on Computer Vision. Springer, Cham, 2025.](https://arxiv.org/pdf/2401.09340)
> 
> [2] [Chen, Jiaqi, et al. "Mapgpt: Map-guided prompting with adaptive path planning for vision-and-language navigation." Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers). 2024.](https://arxiv.org/abs/2401.07314)
> 
> [3] [Qiao, Yanyuan, et al. "Open-Nav: Exploring Zero-Shot Vision-and-Language Navigation in Continuous Environment with Open-Source LLMs." arXiv preprint arXiv:2409.18794 (2024).](https://arxiv.org/pdf/2409.18794)

@GengzeZhou Thank you for your reply. Can I understand it correctly that after extracting image features using the [code](https://github.com/cshizhe/VLN-HAMT/blob/main/preprocess/precompute_img_features_vit.py) you provided, I need to use the BLIP2 model to process the generated hdf5 file in order to obtain image captions?

**Comment by GengzeZhou** [comment]
From [here](https://github.com/cshizhe/VLN-HAMT/blob/c8b9ee12125f9fe36c51d2ab928fde38f7d846bd/preprocess/precompute_img_features_vit.py#L79C1-L94C33) you obtain the rendered images from the simulator and just operate on the original images.

You can change the configuration of the simulator to render images with the desired size and FoV.
