### ISSUE TITLE
从图像到LLM的prompt

### ISSUE THREAD

**Issue by lzz0806** [GengzeZhou/NavGPT#14]
您好您的文章写的非常好，我正在学习您的代码，但是我很好奇您的R2R数据中的obseration_list是如何生成的呢？以及在您的代码中如何将图像数据集的东西生成LLM的prompt呢？

**Comment by GengzeZhou** [comment]
Please refer to this issue #13 which addresses your concern.

You can always render the observation using your configuration (e.g., 4 images with FoV 90° or 36 images with FoV 60°), and pre-caption these images to represent the viewpoints as text descriptions, thereby eliminating the need to access the original images during inference (i.e. load the pre-stored observation descriptions from .json files without interacting with the simulator).
