### ISSUE TITLE
Results Reproducibility

### ISSUE THREAD

**Issue by liangchild** [GengzeZhou/NavGPT#3]
I used GPT4 to reproduce the results in the paper exactly according to your configuration. Unfortunately, I only achieved 30 and 24.48 in SR, SPL, and metrics, which did not meet the 34 and 29 in the paper.
![1705909639338](https://github.com/GengzeZhou/NavGPT/assets/125423087/ec7de4a5-a17d-4d55-b591-07267b8f7eab)

It is worth noting that when I replace it with 3.5, SR and SPL only have 0.
![1705909675290](https://github.com/GengzeZhou/NavGPT/assets/125423087/f4b78f9e-6463-4534-9f73-c309e1a05f9b)

Could you please let me know if there are any other configurations that need to be modified?

**Comment by GengzeZhou** [comment]
With the config `--iters n`, it means only to validate the first _**n**_ samples from the entire dataset split you choose. This is for you to try out NavGPT because validating the entire dataset cost a lot.
Remove this line to validate the entire desired dataset split as indicated in the README.md
