### ISSUE TITLE
Question about cost

### ISSUE THREAD

**Issue by smzzl** [GengzeZhou/NavGPT#4]
Thank you for you work!
I wander how much does it cost for an entire unseen-split-test?

**Comment by GengzeZhou** [comment]
The cost of calling OpenAI’s API with GPT-4 8K context model is $0.03 per 1K input tokens and $0.06 per 1K output tokens by May 2023. Evaluating NavGPT on the entire validation unseen data split, which contains 2,349 trajectories, costs $1762.28.
