### ISSUE TITLE
turned_angle normalize

### ISSUE THREAD

**Issue by smzzl** [GengzeZhou/NavGPT#5]
Thank you for your work! 
In [https://github.com/GengzeZhou/NavGPT/blob/master/nav_src/agent.py#L649](https://chat.openai.com/c/url), why isn't this value normalized using 'normalize_angle', is it intentional or unintentional?

**Comment by GengzeZhou** [comment]
The normalization here is to normalize the absolute orientation to range `[-pi, pi]`, while the turned angle is just a relative number.

**Comment by smzzl** [comment]
> The normalization here is to normalize the absolute orientation to range `[-pi, pi]`, while the turned angle is just a relative number.

I know turned angle is a relative number, but using "Turn heading direction 30 degrees" instead of "Turn heading direction -330 degrees" isn't a better choice?
The expensive cost of GPT-4 testing makes it impossible for me to perform ablation testing on it, so I would like to know if you have discussed it before.
I‘m following your work to do some research.

**Comment by GengzeZhou** [comment]
I agree with you that normalizing the turned angle is better for human reading, but such a small modification in the prompt would not necessarily improve the performance of LLM agents.

The bottleneck of NavGPT lies in the perception of the language model (in NavGPT is the accuracy and granularity of VLM) and the understanding of interaction in the simulator (i.e. to understand the consequence brought by the actions).

**Comment by smzzl** [comment]
Thank you for you explanation, I decide to keep your seting.
