### ISSUE TITLE
Questions about how to calculate the relative heading angle of object

### ISSUE THREAD

**Issue by Leon022** [GengzeZhou/NavGPT#7]
Hello, @GengzeZhou ,
Thanks again for your work, I have aquestion about the relative heading angle.
I notice you mentioned in the paper, "In this work, we utilize Fast-RCNN to extract the bounding boxes of objects in each egocentric view. After locating the objects, we calculate the relative heading angle for each object and the agent." I'm curious about how you calculate the relative heading angle.

My understanding is as follows: (1) Locate the center coordinates of the object box; (2) Calculate the offset of the center point relative to the image center point; (3) Calculate the angle of the object box relative to the image center point based on the offset; (4) Add the angle of the object box to the angle of the image center point to obtain the relative heading angle.

Could you confirm if my understanding is correct? Looking forward to your response.

**Comment by GengzeZhou** [comment]
That is the correct way to obtain the absolute angles for objects. During navigation, the relative angle is calculated as the disparity between the agent's current heading and the absolute angle of objects.
