### ISSUE TITLE
prompt template

### ISSUE THREAD

**Issue by hbw2355265** [GengzeZhou/NavGPT#9]
Do I need to modify the planner_prompt if I use llama or another large language model？

**Comment by GengzeZhou** [comment]
Yes, you would need to properly prompt specific language models for better performance.

Moreover, the Llama model (Llama 2 70B) performed poorly in our preliminary experiments, so it is recommended to consider finetuning the opensource models with the latest techniques (e.g. LangNav, NavCoT, NaviLLM, NavGPT-2) for VLN tasks.
